### ISSUE TITLE
Add synchronous Executor

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/cluster_tools#11]
We currently have a sequential executor, but it's not the same as running the code synchronously. For example, in the case of an error, the next job is executed, instead of failing immediately.

I think it would be helpful to have an executor which executes its function directly on `submit()` and returns a resolved future.

**Comment by philippotto** [comment]
Why not simply use `executor.submit().result()`? This will block the call, raise an error if one occurred and also it works for all existing executor classes. I would be careful with adding new subclasses for such subtle changes in behavior, as they are hard to combine.

**Comment by georgwiese** [comment]
Not sure what you mean by hard to combine?

`executor.submit().result()` would require changes in the code, depending on which behavior we want. It would be nice if we could achieve it by just passing a different executor argument.

For another use case, I'm not sure how easy debugging works with the current sequential executor, as the code is still executed in a new process.

**Comment by philippotto** [comment]
> For another use case, I'm not sure how easy debugging works with the current sequential executor, as the code is still executed in a new process.

Ok, for this use case I agree with you. This might be useful for debugging.

> executor.submit().result() would require changes in the code, depending on which behavior we want. It would be nice if we could achieve it by just passing a different executor argument.

Why would you want to change this control flow behavior from the command line? Also for debugging purposes? Otherwise, I'm not sure why this would be desirable. The executor model defines an async submit method and I'd want to avoid changing this between the subclasses, as it makes writing code (which works for all subclasses) more complicated. If you want to influence this because "in the case of an error, the next job is executed, instead of failing immediately.", I'd argue that this should be tackled independent of executor subclass.

> Not sure what you mean by hard to combine?

Let's say, we add another subclass for this and later somebody wants a slurm executor which blocks on submit. Then, we cannot (i.e., it's cumbersome) combine these two behaviors, as they are implemented in different subclasses.

I'm recognizing now, we should talk in person about this :)

**Comment by hotzenklotz** [comment]
No long relevant.
