### ISSUE TITLE
Log forwarding

### ISSUE THREAD

**Issue by normanrz** [scalableminds/cluster_tools#58]
When running tasks it would convenient to see the log of subtasks directly in the console instead of fishing them out of the slurm logs. Both stdout and stderr. This could be a flag of the executor.

**Comment by normanrz** [comment]
@philippotto what is your take?

**Comment by philippotto** [comment]
Hmm, it could get quite noisy / overwhelming if all the logs are pushed to the same stdout (think of 40 jobs which are simultaneously writing to stdout). But I understand that this can be useful. So, as an opt-in-feature this might be good to have.

Personally, what I'd find really cool would be an interactive command line (dashboard style), where I can switch between different output modes. Then, I could also toggle a "show logs of children"-feature or filter between specific children. However, this is probably not really in the scope of the project yet (would probably need to be implemented on the application-side, too, instead of the cluster tools).
