### ISSUE TITLE
clean up argument passing for subjobs

### ISSUE THREAD

**Issue by fm3** [scalableminds/cluster_tools#62]
Quoting @striebel:
> We should think about an alternative to those all_args, pinging @philippotto
> Also I noted this pattern:
> 
> `args = zip_with_scalar(…)`
> `executor.map(f, args)`
> 
> Maybe the executor could have direct support for this (e.g. `executor.map(func, scalar_arg, *constant_args)`?

**Comment by jstriebel** [comment]
[link to the original comment in `segmentation_tools`](https://github.com/scalableminds/segmentation-tools/pull/663#discussion_r311523298)

**Comment by philippotto** [comment]
I gave this issue some thoughts and came two the following train of thought:

- The current interface makes two things cumbersome: (a) spreading a constant to all jobs requires something like `zip_with_scalar` (b) variadic parameters have to be wrapped (e.g., into a tuple) and unwrapped within the subjob function
- In general, I'd like to keep the interface of the clustertools as close to the python executors as possible, as deviations can get quite confusing and extensions of the interface don't scale well implementation-wise since we have several subclasses of the executors which all need to implement all methods
- Solution for (a): Currying can solve the problem quite elegantly without changing the clustertools interface. Luckily, partially applied functions can be pickled by (not completely outdated) python. The code would look as follows:

```python
from functools import partial

def fn(constant_arg1, constant_arg2, variable_arg):
    return constant_arg1 * constant_arg2 * variable_arg


def test_partials():
    with cluster_tools.get_executor("multiprocessing"):
        result = list(exc.map(partial(fn, 3, 4), [4, 5]))
        assert result == [48, 60]
```
- Solution for (b): Only implementing something like `starmap` comes to my mind, but as I said above: I don't want to extend the interface any further. Wrapping dynamic args in a (named?) tuple has to be done in any case. And the unpacking part seems okay to me (at least for now). Maybe one could have a decorator which accepts the parameters in a wrapped manner and unwraps them automatically. But this might be too much magic and I'm also not sure how well this plays with `partial`.

Do you agree, @jstriebel @fm3?

**Comment by jstriebel** [comment]
@philippotto That makes sense, yes! I think using `partial` is already enough in most cases.
I think extensions like `starmap` could probably be implemented in the top-level `ClusterExecutor` using abstract classes, not affecting the subclasses. I think it would be a neat extension, but probably not a priority.

**Comment by philippotto** [comment]
> `starmap` could probably be implemented in the top-level `ClusterExecutor` using abstract classes

Yes, this is true for the slurm and pbs executor. But we also provide the `ProcessPoolExecutor` for which this would need to be implemented differently. That's two implementations which might be fine. But strictly speaking we would need the `star` variant also for `map_unordered` and `map_to_futures` since the behavior cuts through these methods, as well. That's why I'd rather find a solution which composes better (e.g., via decorators).

> I think it would be a neat extension, but probably not a priority.

Yes, let's try out `partial` first :)
