### ISSUE TITLE
map_to_futures with empty list crashes, should return empty list

### ISSUE THREAD

**Issue by fm3** [scalableminds/cluster_tools#92]
The resumable executor of voxelytics checks what needs to be re-run. If that list becomes empty, map_to_futures crashes

**Comment by fm3** [comment]
@philippotto You mentioned that fixing this might be blocked by some other issue, I don’t recall what that was exactly, could you repeat that?

**Comment by philippotto** [comment]
Thanks for opening the issue! I created a PR to fix it.

> @philippotto You mentioned that fixing this might be blocked by some other issue, I don’t recall what that was exactly, could you repeat that?

I meant that pulling in the newer cluster tools version is kind of blocked in vx, since there are some interdependencies with the cuber and the mypy upgrade. Once https://github.com/scalableminds/voxelytics/pull/2306 is merged, everything should fall into place hopefully.
